### ISSUE TITLE
.js File not updating after update in HACS

### ISSUE THREAD

**Issue by Borrel88** [Devqon/lovelace-mini-thermostat#15] opened 2020-01-31 18:20 UTC
After updating the plugin in HACS to the newest version (v0.1.0) the javascript file won't update. Though HACS is showing the correct updated version number.

The newest configuration options are not working and not visible anywhere in the .js file.

- Reinstalling is not working
- Uninstalling and then install again is also not working

**Comment by martinhoess** [comment] 2020-01-31 20:14
Can confirm this / have the same problem.

The js file from the release however seem to be the correct one ... if you download it an replace the existing one in the lovelace/plugin folder the grouped/tiny stuff works

**Comment by Devqon** [comment] 2020-01-31 20:19
I am not sure why this happens, possibly a mismatch with how it is supposed to work for HACS. Does the logs say anything?

**Comment by Borrel88** [comment] 2020-01-31 20:43
Nothing visible in the logs.
Cannot find a specific hacs or component log, should there be any?

**Comment by Borrel88** [comment] 2020-01-31 21:00
Found a (temporary?) solution.

In the www/community/lovelace-m8ni-thermostat folder. I deleted the .gz file which is used by HACS to deliver the custom component to the viewer at a faster speed then a regular uncompressed .js file.

After removing the file, the newest version of the card is correctly showing.

**Comment by Devqon** [comment] 2020-02-01 12:01
I think it has to do with https://github.com/hacs/integration/issues/922

The developer of HACS advises to use this workaround:
"if you use releases, if't probably the same root cause as this https://github.com/hacs/integration/issues/922
Try selecting "master", then selecting the nevest version, the click the tree dots -> reload data.
Then update"

**Comment by Devqon** [comment] 2020-02-03 11:01
Closing this as it is a bug in HACS, not this plugin

**Closed by Devqon** 2020-02-03 11:01 UTC
Labels: bug
